// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: windows_32

#ifndef _WINDOWS_32_UI_H
#define _WINDOWS_32_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
void revealLogo_Animation( lv_obj_t *TargetObject, int delay);
void showBars_Animation( lv_obj_t *TargetObject, int delay);
void maximize_Animation( lv_obj_t *TargetObject, int delay);
void minimize_Animation( lv_obj_t *TargetObject, int delay);
void hideWindow_Animation( lv_obj_t *TargetObject, int delay);
void showWindow_Animation( lv_obj_t *TargetObject, int delay);
void closeApp_Animation( lv_obj_t *TargetObject, int delay);
void closeSettings_Animation( lv_obj_t *TargetObject, int delay);
void openSettings_Animation( lv_obj_t *TargetObject, int delay);
void openApp_Animation( lv_obj_t *TargetObject, int delay);
void moveXinfinite_Animation( lv_obj_t *TargetObject, int delay);
void openSimulator_Animation( lv_obj_t *TargetObject, int delay);
void showSimulator_Animation( lv_obj_t *TargetObject, int delay);
void ui_event_boot( lv_event_t * e);
extern lv_obj_t *ui_boot;
extern lv_obj_t *ui_loader;
extern lv_obj_t *ui_bootLogo;
void ui_event_desktop( lv_event_t * e);
extern lv_obj_t *ui_desktop;
extern lv_obj_t *ui_wallpaper;
void ui_event_appWindow( lv_event_t * e);
extern lv_obj_t *ui_appWindow;
extern lv_obj_t *ui_appIconFiles;
extern lv_obj_t *ui_settingsAppLabel1;
extern lv_obj_t *ui_appActions1;
void ui_event_appMinMax1( lv_event_t * e);
extern lv_obj_t *ui_appMinMax1;
void ui_event_apphide1( lv_event_t * e);
extern lv_obj_t *ui_apphide1;
void ui_event_appClose1( lv_event_t * e);
extern lv_obj_t *ui_appClose1;
extern lv_obj_t *ui_settingsListPanel1;
extern lv_obj_t *ui_settingsTitleList1;
extern lv_obj_t *ui_settingsTitleListItem5;
extern lv_obj_t *ui_settingsListIcon5;
extern lv_obj_t *ui_settingsListLabel5;
extern lv_obj_t *ui_settingsTitleListItem6;
extern lv_obj_t *ui_settingsListIcon6;
extern lv_obj_t *ui_settingsListLabel6;
extern lv_obj_t *ui_settingsTitleListItem7;
extern lv_obj_t *ui_settingsListIcon7;
extern lv_obj_t *ui_settingsListLabel7;
extern lv_obj_t *ui_settingsTitleListItem8;
extern lv_obj_t *ui_settingsListIcon8;
extern lv_obj_t *ui_settingsListLabel8;
extern lv_obj_t *ui_fileExplorerPanel;
extern lv_obj_t *ui_folderPanel;
extern lv_obj_t *ui_desktoppanel;
extern lv_obj_t *ui_deskotpLabel;
extern lv_obj_t *ui_desktopIcon;
extern lv_obj_t *ui_docsPanel;
extern lv_obj_t *ui_documentsLabel;
extern lv_obj_t *ui_documentsIcon;
extern lv_obj_t *ui_downloadsPanel;
extern lv_obj_t *ui_downloadsLabel;
extern lv_obj_t *ui_downloadsIcon;
extern lv_obj_t *ui_musicFolderPanel;
extern lv_obj_t *ui_musicLabel;
extern lv_obj_t *ui_musicIcon;
extern lv_obj_t *ui_storagePanel;
extern lv_obj_t *ui_hardDiskPanel;
extern lv_obj_t *ui_hardDiskLabel;
extern lv_obj_t *ui_storageSizebar;
extern lv_obj_t *ui_diskIcon;
extern lv_obj_t *ui_spaceLabel;
extern lv_obj_t *ui_drivePanel;
extern lv_obj_t *ui_driveLabel;
extern lv_obj_t *ui_driveIcon;
extern lv_obj_t *ui_chronoApp;
extern lv_obj_t *ui_appIconFiles1;
extern lv_obj_t *ui_appActions2;
void ui_event_appMinMax2( lv_event_t * e);
extern lv_obj_t *ui_appMinMax2;
void ui_event_apphide2( lv_event_t * e);
extern lv_obj_t *ui_apphide2;
void ui_event_appClose2( lv_event_t * e);
extern lv_obj_t *ui_appClose2;
extern lv_obj_t *ui_settingsAppLabel2;
extern lv_obj_t *ui_chronosImage;
extern lv_obj_t *ui_playlogo;
extern lv_obj_t *ui_qrLabel;
extern lv_obj_t *ui_chronosQR;
void ui_event_settingsWindow( lv_event_t * e);
extern lv_obj_t *ui_settingsWindow;
void ui_event_settingsAppIcon( lv_event_t * e);
extern lv_obj_t *ui_settingsAppIcon;
extern lv_obj_t *ui_settingsAppLabel;
extern lv_obj_t *ui_appActions;
void ui_event_appMinMax( lv_event_t * e);
extern lv_obj_t *ui_appMinMax;
void ui_event_apphide( lv_event_t * e);
extern lv_obj_t *ui_apphide;
void ui_event_appClose( lv_event_t * e);
extern lv_obj_t *ui_appClose;
extern lv_obj_t *ui_myInfopanel;
extern lv_obj_t *ui_userLabel;
extern lv_obj_t *ui_userInfo;
extern lv_obj_t *ui_userIcon;
extern lv_obj_t *ui_settingsGridPanel;
void ui_event_systemPanel( lv_event_t * e);
extern lv_obj_t *ui_systemPanel;
extern lv_obj_t *ui_systemText;
extern lv_obj_t *ui_systemTitle;
extern lv_obj_t *ui_systemIcon;
extern lv_obj_t *ui_systemPanel1;
extern lv_obj_t *ui_systemText1;
extern lv_obj_t *ui_systemTitle1;
extern lv_obj_t *ui_systemIcon1;
extern lv_obj_t *ui_systemPanel2;
extern lv_obj_t *ui_systemText2;
extern lv_obj_t *ui_systemTitle2;
extern lv_obj_t *ui_systemIcon2;
extern lv_obj_t *ui_systemPanel3;
extern lv_obj_t *ui_systemText3;
extern lv_obj_t *ui_systemTitle3;
extern lv_obj_t *ui_systemIcon3;
extern lv_obj_t *ui_systemPanel4;
extern lv_obj_t *ui_systemText4;
extern lv_obj_t *ui_systemTitle4;
extern lv_obj_t *ui_systemIcon4;
extern lv_obj_t *ui_systemPanel5;
extern lv_obj_t *ui_systemText5;
extern lv_obj_t *ui_systemTitle5;
extern lv_obj_t *ui_systemIcon5;
extern lv_obj_t *ui_settingsListPanel;
extern lv_obj_t *ui_settingsTitleList;
void ui_event_settingsTitleListItem( lv_event_t * e);
extern lv_obj_t *ui_settingsTitleListItem;
extern lv_obj_t *ui_settingsListIcon;
extern lv_obj_t *ui_settingsListLabel;
extern lv_obj_t *ui_settingsTitleListItem3;
extern lv_obj_t *ui_settingsListIcon3;
extern lv_obj_t *ui_settingsListLabel3;
extern lv_obj_t *ui_settingsTitleListItem2;
extern lv_obj_t *ui_settingsListIcon2;
extern lv_obj_t *ui_settingsListLabel2;
void ui_event_settingsTitleListItem4( lv_event_t * e);
extern lv_obj_t *ui_settingsTitleListItem4;
extern lv_obj_t *ui_settingsListIcon4;
extern lv_obj_t *ui_settingsListLabel4;
extern lv_obj_t *ui_displaySettingsPanel;
extern lv_obj_t *ui_brightnessLabel;
extern lv_obj_t *ui_sliderBrightness;
extern lv_obj_t *ui_wallpaperLabel;
extern lv_obj_t *ui_wallpaperPanel;
void ui_event_buttonSpace( lv_event_t * e);
extern lv_obj_t *ui_buttonSpace;
extern lv_obj_t *ui_labelSpace;
void ui_event_buttonFbiego( lv_event_t * e);
extern lv_obj_t *ui_buttonFbiego;
extern lv_obj_t *ui_fbiegoLabel;
extern lv_obj_t *ui_scaleLabel;
extern lv_obj_t *ui_scaleDropdown;
extern lv_obj_t *ui_resLabel;
extern lv_obj_t *ui_resDropdown;
extern lv_obj_t *ui_displayLabel;
extern lv_obj_t *ui_detectButton;
extern lv_obj_t *ui_detectLabel;
extern lv_obj_t *ui_displaySettingsPanel2;
extern lv_obj_t *ui_deviceSpecLabel;
extern lv_obj_t *ui_deviceSpecInfo;
extern lv_obj_t *ui_winSpecLabel;
extern lv_obj_t *ui_winSpecInfo;
extern lv_obj_t *ui_designLabel;
extern lv_obj_t *ui_myInfopanel1;
extern lv_obj_t *ui_userInfoLabel;
extern lv_obj_t *ui_userInfoText;
extern lv_obj_t *ui_userInfoIcon;
extern lv_obj_t *ui_taskBar;
void ui_event_startIconPanel( lv_event_t * e);
extern lv_obj_t *ui_startIconPanel;
extern lv_obj_t *ui_startIcon;
void ui_event_startIconPanel1( lv_event_t * e);
extern lv_obj_t *ui_startIconPanel1;
extern lv_obj_t *ui_filesIcon;
void ui_event_startIconPanel2( lv_event_t * e);
extern lv_obj_t *ui_startIconPanel2;
void ui_event_settingsIcon( lv_event_t * e);
extern lv_obj_t *ui_settingsIcon;
void ui_event_startIconPanel3( lv_event_t * e);
extern lv_obj_t *ui_startIconPanel3;
void ui_event_settingsIcon1( lv_event_t * e);
extern lv_obj_t *ui_settingsIcon1;
void ui_event_startIconPanel4( lv_event_t * e);
extern lv_obj_t *ui_startIconPanel4;
void ui_event_settingsIcon2( lv_event_t * e);
extern lv_obj_t *ui_settingsIcon2;
void ui_event_statusBar( lv_event_t * e);
extern lv_obj_t *ui_statusBar;
extern lv_obj_t *ui_timeLabel;
extern lv_obj_t *ui_dateLabel;
extern lv_obj_t *ui_statusIcons;
extern lv_obj_t *ui_batteryIcon;
extern lv_obj_t *ui_wifiIcon;
extern lv_obj_t *ui_speakerIcon;
void ui_event_weatherBar( lv_event_t * e);
extern lv_obj_t *ui_weatherBar;
extern lv_obj_t *ui_weatherItemIcon;
extern lv_obj_t *ui_weatherItemTemp;
extern lv_obj_t *ui_weatherLabel;
extern lv_obj_t *ui_startMenu;
void ui_event_desktopSearch( lv_event_t * e);
extern lv_obj_t *ui_desktopSearch;
extern lv_obj_t *ui_searchIcon;
extern lv_obj_t *ui_startApps;
void ui_event_appStartItem( lv_event_t * e);
extern lv_obj_t *ui_appStartItem;
extern lv_obj_t *ui_appItemLabel;
extern lv_obj_t *ui_appItemIcon;
void ui_event_appStartItem1( lv_event_t * e);
extern lv_obj_t *ui_appStartItem1;
extern lv_obj_t *ui_appItemLabel1;
extern lv_obj_t *ui_appItemIcon1;
void ui_event_appStartItem2( lv_event_t * e);
extern lv_obj_t *ui_appStartItem2;
extern lv_obj_t *ui_appItemLabel2;
extern lv_obj_t *ui_appItemIcon2;
extern lv_obj_t *ui_appStartItem6;
extern lv_obj_t *ui_appItemLabel6;
extern lv_obj_t *ui_appItemIcon6;
extern lv_obj_t *ui_appStartItem4;
extern lv_obj_t *ui_appItemLabel4;
extern lv_obj_t *ui_appItemIcon4;
extern lv_obj_t *ui_appStartItem5;
extern lv_obj_t *ui_appItemLabel5;
extern lv_obj_t *ui_appItemIcon5;
extern lv_obj_t *ui_appStartItem3;
extern lv_obj_t *ui_appItemLabel3;
extern lv_obj_t *ui_appItemIcon3;
extern lv_obj_t *ui_actionPanel;
extern lv_obj_t *ui_dateTimeLabel;
extern lv_obj_t *ui_volumeSlider;
extern lv_obj_t *ui_speakerAction;
extern lv_obj_t *ui_wifiButton;
extern lv_obj_t *ui_batteryBar;
extern lv_obj_t *ui_batteryAction;
extern lv_obj_t *ui_bleButton;
extern lv_obj_t *ui_keyboard;
extern lv_obj_t *ui_iosSimulator;
extern lv_obj_t *ui_appIconFiles2;
extern lv_obj_t *ui_iosPanel;
extern lv_obj_t *ui_appActions3;
void ui_event_apphide3( lv_event_t * e);
extern lv_obj_t *ui_apphide3;
void ui_event_appClose3( lv_event_t * e);
extern lv_obj_t *ui_appClose3;
extern lv_obj_t *ui_settingsAppLabel3;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_logo_panlee_png);   // assets\logo_panlee.png
LV_IMG_DECLARE( ui_img_wallpaper_1_png);   // assets\wallpaper_1.png
LV_IMG_DECLARE( ui_img_folder_png);   // assets\folder.png
LV_IMG_DECLARE( ui_img_inside_png);   // assets\inside.png
LV_IMG_DECLARE( ui_img_resize_png);   // assets\resize.png
LV_IMG_DECLARE( ui_img_minus_png);   // assets\minus.png
LV_IMG_DECLARE( ui_img_close_png);   // assets\close.png
LV_IMG_DECLARE( ui_img_recent_png);   // assets\recent.png
LV_IMG_DECLARE( ui_img_time_png);   // assets\time.png
LV_IMG_DECLARE( ui_img_computer_png);   // assets\computer.png
LV_IMG_DECLARE( ui_img_netwrok_files_png);   // assets\netwrok_files.png
LV_IMG_DECLARE( ui_img_desktop_files_png);   // assets\desktop_files.png
LV_IMG_DECLARE( ui_img_documents_png);   // assets\documents.png
LV_IMG_DECLARE( ui_img_downloads_png);   // assets\downloads.png
LV_IMG_DECLARE( ui_img_music_png);   // assets\music.png
LV_IMG_DECLARE( ui_img_hard_drive_png);   // assets\hard_drive.png
LV_IMG_DECLARE( ui_img_cd_drive_png);   // assets\cd_drive.png
LV_IMG_DECLARE( ui_img_chr_r_png);   // assets\chr_r.png
LV_IMG_DECLARE( ui_img_chr_home_png);   // assets\chr_home.png
LV_IMG_DECLARE( ui_img_g_play_png);   // assets\g_play.png
LV_IMG_DECLARE( ui_img_chr_qr_png);   // assets\chr_qr.png
LV_IMG_DECLARE( ui_img_settings_png);   // assets\settings.png
LV_IMG_DECLARE( ui_img_flx_r_png);   // assets\flx_r.png
LV_IMG_DECLARE( ui_img_system_png);   // assets\system.png
LV_IMG_DECLARE( ui_img_mouse_png);   // assets\mouse.png
LV_IMG_DECLARE( ui_img_internet_png);   // assets\internet.png
LV_IMG_DECLARE( ui_img_application_png);   // assets\application.png
LV_IMG_DECLARE( ui_img_personalization_png);   // assets\personalization.png
LV_IMG_DECLARE( ui_img_user_png);   // assets\user.png
LV_IMG_DECLARE( ui_img_monitor_png);   // assets\monitor.png
LV_IMG_DECLARE( ui_img_server_png);   // assets\server.png
LV_IMG_DECLARE( ui_img_charge_png);   // assets\charge.png
LV_IMG_DECLARE( ui_img_information_png);   // assets\information.png
LV_IMG_DECLARE( ui_img_flx_bg_png);   // assets\flx_bg.png
LV_IMG_DECLARE( ui_img_windows_png);   // assets\windows.png
LV_IMG_DECLARE( ui_img_ios_png);   // assets\ios.png
LV_IMG_DECLARE( ui_img_battery_png);   // assets\battery.png
LV_IMG_DECLARE( ui_img_wifi_icon_png);   // assets\wifi_icon.png
LV_IMG_DECLARE( ui_img_speaker_png);   // assets\speaker.png
LV_IMG_DECLARE( ui_img_cloudy_png);   // assets\cloudy.png
LV_IMG_DECLARE( ui_img_search_png);   // assets\search.png
LV_IMG_DECLARE( ui_img_cortana_png);   // assets\cortana.png
LV_IMG_DECLARE( ui_img_lumia_png);   // assets\lumia.png
LV_IMG_DECLARE( ui_img_rts_r_png);   // assets\rts_r.png
LV_IMG_DECLARE( ui_img_bt_png);   // assets\bt.png
LV_IMG_DECLARE( ui_img_1393274193);   // assets\flx-white-200.png
LV_IMG_DECLARE( ui_img_473727351);   // assets\rfid-128.png
LV_IMG_DECLARE( ui_img_1890958998);   // assets\check-128.png
LV_IMG_DECLARE( ui_img_1095992510);   // assets\cancel-128.png
LV_IMG_DECLARE( ui_img_196738267);   // assets\flx-200.png
LV_IMG_DECLARE( ui_img_2_png);   // assets\2.png
LV_IMG_DECLARE( ui_img_1_png);   // assets\1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
