// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: windows_32

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onFilePressed(lv_event_t * e);
void onSettingsPressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
