// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: windows_32

#include "ui.h"

void onFilePressed(lv_event_t * e)
{
	// Your code here
	// lv_obj_t * obj = lv_event_get_target(e);

    // lv_indev_t * indev = lv_indev_get_act();
    // if(indev == NULL)  return;

    // lv_point_t vect;
    // lv_indev_get_vect(indev, &vect);

    // lv_coord_t x = lv_obj_get_x(obj) + vect.x;
    // lv_coord_t y = lv_obj_get_y(obj) + vect.y;
    // lv_obj_set_pos(obj, x, y);
}

void onSettingsPressed(lv_event_t * e)
{
	// Your code here
	// lv_obj_t * obj = lv_event_get_target(e);

    // lv_indev_t * indev = lv_indev_get_act();
    // if(indev == NULL)  return;

    // lv_point_t vect;
    // lv_indev_get_vect(indev, &vect);

    // lv_coord_t x = lv_obj_get_x(obj) + vect.x;
    // lv_coord_t y = lv_obj_get_y(obj) + vect.y;
    // lv_obj_set_pos(obj, x, y);
}
